/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        cream: "var(--color-cream)",
        "cream-deep": "var(--color-cream-deep)",
        ink: "var(--color-ink)",
        "ink-soft": "var(--color-ink-soft)",
        primary: "var(--color-primary)",
        primarybtn: "var(--color-primary-btn)",
        primarydark: "var(--color-primary-dark)",
        primarydeep: "var(--color-primary-deep)",
        primaryink: "var(--color-primary-ink)",
        accent: "var(--color-accent)",
        accentdark: "var(--color-accent-dark)",
        accentink: "var(--color-accent-ink)",
        sunny: "var(--color-sunny)",
        sunnydark: "var(--color-sunny-dark)",
        sunnyink: "var(--color-sunny-ink)",
        mint: "var(--color-mint)",
        mintdeep: "var(--color-mint-deep)",
        coral: "var(--color-coral)",
        coraldark: "var(--color-coral-dark)",
        coralink: "var(--color-coral-ink)",
        sky: "var(--color-sky)",
        skydark: "var(--color-sky-dark)",
        skyink: "var(--color-sky-ink)",
        grape: "var(--color-grape)",
        grapedark: "var(--color-grape-dark)",
        grapeink: "var(--color-grape-ink)",
        card: "var(--color-card)",
        line: "var(--color-line)",
        "line-soft": "var(--color-line-soft)",
        muted: "var(--color-muted)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        card: "var(--radius-card)",
        chunky: "var(--radius-chunky)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
      },
      fontFamily: {
        sans: ["var(--font-body)", "Nunito", "ui-rounded", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "Fredoka", "Nunito", "ui-rounded", "system-ui", "sans-serif"],
      },
      fontSize: {
        "kid-xs": ["0.8125rem", { lineHeight: "1.4" }],
        "kid-sm": ["1rem", { lineHeight: "1.5" }],
        "kid-base": ["1.125rem", { lineHeight: "1.55" }],
        "kid-lg": ["1.375rem", { lineHeight: "1.4" }],
        "kid-xl": ["1.75rem", { lineHeight: "1.25" }],
        "kid-2xl": ["2.25rem", { lineHeight: "1.15" }],
        "kid-3xl": ["3rem", { lineHeight: "1.08" }],
        // Fluid hero sizes — scale with the viewport, capped for tablets.
        "kid-hero": ["clamp(2.25rem, 8.5vw, 3.25rem)", { lineHeight: "1.05" }],
        "kid-mega": ["clamp(3rem, 14vw, 5rem)", { lineHeight: "1" }],
      },
      boxShadow: {
        chunky: "var(--shadow-chunky)",
        "chunky-sm": "var(--shadow-chunky-sm)",
        "chunky-lg": "var(--shadow-chunky-lg)",
        float: "var(--shadow-float)",
        lift: "var(--shadow-lift)",
        pop: "0 6px 0 rgba(43,38,32,0.18), 0 12px 24px rgba(43,38,32,0.12)",
      },
      transitionTimingFunction: {
        soft: "cubic-bezier(0.22, 0.9, 0.28, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      keyframes: {
        "duo-pop": {
          "0%": { transform: "scale(0.6)", opacity: "0" },
          "60%": { transform: "scale(1.08)", opacity: "1" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "duo-wiggle": {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        "duo-bounce-soft": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "duo-float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "duo-shine": {
          "0%": { transform: "translateX(-100%) skewX(-20deg)" },
          "100%": { transform: "translateX(220%) skewX(-20deg)" },
        },
        "mt-rise": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "mt-xp-fly": {
          "0%": { transform: "translateY(6px) scale(0.9)", opacity: "0" },
          "22%": { transform: "translateY(-6px) scale(1.06)", opacity: "1" },
          "72%": { transform: "translateY(-22px) scale(1)", opacity: "1" },
          "100%": { transform: "translateY(-40px) scale(0.98)", opacity: "0" },
        },
        "mt-medal": {
          "0%": { transform: "scale(0.4) rotate(-18deg)", opacity: "0" },
          "55%": { transform: "scale(1.18) rotate(6deg)", opacity: "1" },
          "78%": { transform: "scale(0.96) rotate(-2deg)" },
          "100%": { transform: "scale(1) rotate(0deg)", opacity: "1" },
        },
        "mt-flicker": {
          "0%, 100%": { transform: "scale(1) rotate(-1.5deg)", opacity: "1" },
          "35%": { transform: "scale(1.07) rotate(1.5deg)", opacity: "0.94" },
          "70%": { transform: "scale(0.98) rotate(-0.5deg)", opacity: "1" },
        },
        "mt-slide-up": {
          "0%": { transform: "translateY(24px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "duo-pop": "duo-pop 300ms cubic-bezier(0.34, 1.56, 0.64, 1) both",
        "duo-wiggle": "duo-wiggle 480ms ease-in-out",
        "duo-bounce-soft": "duo-bounce-soft 900ms ease-in-out infinite",
        "duo-float": "duo-float 2600ms ease-in-out infinite",
        "duo-shine": "duo-shine 2400ms ease-in-out infinite",
        "mt-rise": "mt-rise 360ms cubic-bezier(0.22, 0.9, 0.28, 1) both",
        "mt-xp-fly": "mt-xp-fly 1200ms cubic-bezier(0.22, 0.9, 0.28, 1) both",
        "mt-medal": "mt-medal 720ms cubic-bezier(0.34, 1.56, 0.64, 1) both",
        "mt-flicker": "mt-flicker 1400ms ease-in-out infinite",
        "mt-slide-up": "mt-slide-up 360ms cubic-bezier(0.22, 0.9, 0.28, 1) both",
      },
    },
  },
  plugins: [],
};
